### PR TITLE
Adding Google Doc HTML to Markdown function

### PR DESCRIPTION
**Pull request by noamross**
I needed this function, and I thought your package would be an appropriate place to put it.  Google Docs' HTML export is a little weird.  This pre-processes the HTML to deal with three specific weirdnesses I've dealt with: bold and italic formatting is set using classes, not `<strong>` or `<em>`, and Google converts all links to versions that go through google for tracking purposes.  This fixes those, and converts through `rmarkdown::pandoc_convert` with some appropriate options to get a clean result.

Happy to write some specific tests for this.  Figured you would want to get a test written for `download_file` and I could piggy back off whatever example you want for that.

### CODE REVIEW

**Comment by Ironholds** [comment]
(don't worry, Travis is broken. Bah.)

First: thank you for all the hard work! This is fantastic and is really good to have - I imagine it'll be most appreciated by users :). I particularly like the stringi use - more people need to build with that package.

Second...and I really hate to be this person, because like I said, this is (a lot of) fantastic work: could you rebuild iterating off Hadley's xml2 package, if you find it to be stable enough? From a maintainability point of view I try to avoid DTL's libraries wherever possible, because they tend to be highly inconsistentInSyntax and in documentation. I want to avoid the scenario where something in this parser breaks and someone then ends up with bleeding eyeballs trying to fix it because of the dependencies. Does that make sense?

**Comment by noamross** [comment]
I actually tried to use xml2 at first, but, to quote the README:

>  Currently, the biggest difference is that xml2 provides no way to modify an existing xml document or create a new one.

That's exactly what I needed to do here.  Right now xml2 is just meant for importing data, not manipulating XML.  If Hadley expands xml2's scope, I'd be happy to refactor for all the above reasons.

**Comment by Ironholds** [comment]
Makes sense! Ack; mind rebasing?

**Comment by noamross** [comment]
There you go.

**Comment by Ironholds** [comment]
Yay!

**Pull request merged**
